### ISSUE TITLE
Replace placeimg with another image provider

### ISSUE THREAD

**Issue by gleuch** [anasrar/anasrar.github.io#50]
@anasrar Great blog post at https://anasrar.github.io/blog/generate-image-from-html-using-satori-and-resvg, thank you!

You might want to update your post as https://placeimg.com has shut down as of Jun 2023, which throws an error when running the example code. I recommend replacing the image example with https://placekitten.com.

**Comment by anasrar** [comment]
Done, thanks for the report.
